spring:
  application:
    name: aliyun-oss

server:
  port: 8000

oss:
  aliyun:
    endpoint: https://oss-cn-shenzhen.aliyuncs.com
    bucket-name: bucket
#    RAM用户,https://ram.console.aliyun.com/overview
    access-key-id: LTAI4GHDyrAm1y4RMeUXdM7ra
    access-key-secret: TgjZGqPkWdLNFgYQNukLfTfjADdJjAa
#minio对象存储服务
  minio:
    endpoint: http://192.168.131.139:9000
    accessKey: minioadmin
    secretKey: minioadmin